version: "3"

services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    ports:
      - "4822:4822"

  ssh-server:
    build:
      context: ./
      dockerfile: docker/Dockerfile.ssh-server
    container_name: ssh-server
    hostname: ssh-server

# ubuntu:ubuntu
#  rdp-server:
#    image: scottyhardy/docker-remote-desktop
#    container_name: rdp-server
#    hostname: rdp-server

  rdp-server:
    image: umis/xubuntu-office-xrdp-desktop:v1.0
    container_name: rdp-server
    environment:
      - "USERNAME:root"
      - "PASSWORD:Docker"
    hostname: rdp-server

#  remote-terminal:
#    build: ./
#    ports:
#      - "9528:9528"
