version: "3"

services:
  guacd:
    image: ir0cn/guacd
    container_name: guacd
    ports:
      - "4822:4822"

  ssh-server:
    image: ir0cn/ubuntu
    container_name: ssh-server
    hostname: ssh-server
    environment:
      SSH_PASSWORD: linuxserver

# ubuntu:ubuntu
  rdp-server:
    image: scottyhardy/docker-remote-desktop
    container_name: rdp-server
    hostname: rdp-server

#  rdp-server:
#    image: umis/xubuntu-office-xrdp-desktop:v1.0
#    container_name: rdp-server
#    environment:
#      - "USERNAME:root"
#      - "PASSWORD:Docker"
#    hostname: rdp-server

#  remote-terminal:
#    build: ./
#    ports:
#      - "9528:9528"
